version: '2.1'

services:
  users-db:
    container_name: users-db
    build: https://github.com/0x4e3/flask-sandbox-users.git#master:users/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    command: gunicorn -b 0.0.0.0:5000 manage:app
    build: https://github.com/0x4e3/flask-sandbox-users.git
    ports:
      - 5001:5000
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=users.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  web-service:
    container_name: web-service
    build:
      context: https://github.com/0x4e3/flask-sandbox-client.git
      args:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
      web-service:
        condition: service_started
    links:
      - users-service

  swagger:
    container_name: swagger
    build: https://github.com/0x4e3/flask-sandbox-swagger
    ports:
      - '8080:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=https://raw.githubusercontent.com/0x4e3/flask-sandbox-swagger/master/swagger.json
    depends_on:
      users-service:
        condition: service_started
